# Specify a base image
FROM node:20-alpine

# Specify the work base directory for whenever you copy content into this docker container
WORKDIR /usr/app

# Copy only package.json in current working directory into our image container before installing dependencies.
COPY ./package*.json ./

# Install some dependencies
RUN npm install --force

# Install Angular CLI
RUN npm install -g @angular/cli

ENV GENERATE_SOURCEMAP=false

ENV NODE_OPTIONS="--max_old_space_size=3072"

# Copy every other content in current working directory into our image container after installing dependencies.
COPY ./ ./

# Default command - Use --host 0.0.0.0 to create outside ipv4 url for access
CMD ["npm", "run", "build:docker:test"]

# NOTE: the 'dockerignore' file is used similarly to the same way you use gitignore for github BUT specific for your docker container.


# To Run this docker file - WITHOUT docker-compose.yml file:
# > docker build -t api-v1 --platform linux/amd64 .
# > docker run -p 4200:4200  --platform linux/amd64 api-v1

# Use this to delete all images and build and volumes that are NOT in-use:
# > docker system prune
