
export type CHILD_CARE_VALUES = "NANNIES_OR_RECURRING_SITTERS" | "ONE_TIME_SITTERS" | "DAY_CARE_CENTER";

export type SENIOR_CARE_VALUES = "SENIOR_HOME_CARE" | "RESPITE_CARE" | "HOSPICE_CARE" | "ADULT_DAYCARE";

export type PET_CARE_VALUES = "PET_WALKING" | "PET_FEEDING" | "GENERAL_PETTING";

export type HOUSE_KEEPING_VALUES = "HOMEWORK_CURRICULUM_HELP" | "STRUCTURING_ACTIVITIES" | "LIGHT_HOUSEKEEPING_OR_MEAL_PREP";

export type SecondaryCareType = CHILD_CARE_VALUES | SENIOR_CARE_VALUES | PET_CARE_VALUES | HOUSE_KEEPING_VALUES;

